In [3]:
# Importing libraries
import pandas as pd
import numpy as np

In [59]:
# Reading dataset
df = pd.read_csv(r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv")
print("Shape:", df.shape)
df.head()

Shape: (30894, 20)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,1468,4.834,73.484,1.621,NaN,20.018,NaN,7.472,NaN,101.175,NaN,8.176,NaN,35.215,NaN,53.262,NaN,2.068,NaN
1,2023-08-04 23:30:00,1469,2.544,106.424,1.959,NaN,19.986,NaN,7.455,NaN,100.884,NaN,8.175,NaN,35.209,NaN,53.254,NaN,1.994,NaN
2,2023-08-04 23:00:00,1470,1.260,156.755,1.620,NaN,20.001,NaN,7.430,NaN,100.571,NaN,8.171,NaN,35.207,NaN,53.252,NaN,2.030,NaN
3,2023-08-04 23:30:00,1471,0.760,281.754,1.761,NaN,19.983,NaN,7.419,NaN,100.398,NaN,8.171,NaN,35.211,NaN,53.257,NaN,1.973,NaN
4,2023-08-04 23:00:00,1472,3.397,244.637,1.635,NaN,19.986,NaN,7.429,NaN,100.538,NaN,8.171,NaN,35.208,NaN,53.253,NaN,1.944,NaN

In [9]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30894 entries, 0 to 30893
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 30894 non-null  object
 1   Record number                             30894 non-null  int64
 2   Average Water Speed                       30874 non-null  float64
 3   Average Water Direction                   30893 non-null  float64
 4   Chlorophyll                               30309 non-null  float64
 5   Chlorophyll [quality]                     30086 non-null  float64
 6   Temperature                               25730 non-null  float64
 7   Temperature [quality]                     25550 non-null  float64
 8   Dissolved Oxygen                          26594 non-null  float64
 9   Dissolved Oxygen [quality]                26370 non-null  float64
 10  Dissolved Oxygen (%Saturation)            25145 non-null  float64
 11  Dissolved Oxygen (%Saturation) [quality]  24944 non-null  float64
 12  pH                                        29810 non-null  float64
 13  pH [quality]                              29586 non-null  float64
 14  Salinity                                  26936 non-null  float64
 15  Salinity [quality]                        26712 non-null  float64
 16  Specific Conductance                      29527 non-null  float64
 17  Specific Conductance [quality]            29303 non-null  float64
 18  Turbidity                                 28894 non-null  float64
 19  Turbidity [quality]                       28670 non-null  float64
dtypes: float64(18), int64(1), object(1)
memory usage: 4.7+ MB

Timestamp                                      0
Record number                                  0
Average Water Speed                           20
Average Water Direction                        1
Chlorophyll                                  585
Chlorophyll [quality]                        808
Temperature                                 5164
Temperature [quality]                       5344
Dissolved Oxygen                            4300
Dissolved Oxygen [quality]                  4524
Dissolved Oxygen (%Saturation)              5749
Dissolved Oxygen (%Saturation) [quality]    5950
pH                                          1084
pH [quality]                                1308
Salinity                                    3958
Salinity [quality]                          4182
Specific Conductance                        1367
Specific Conductance [quality]              1591
Turbidity                                   2000
Turbidity [quality]                         2224
dtype: int64

In [11]:
# Fill missing values
df.fillna(df.mean(numeric_only=True), inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

df.isnull().sum()

Timestamp                                   0
Record number                               0
Average Water Speed                         0
Average Water Direction                     0
Chlorophyll                                 0
Chlorophyll [quality]                       0
Temperature                                 0
Temperature [quality]                       0
Dissolved Oxygen                            0
Dissolved Oxygen [quality]                  0
Dissolved Oxygen (%Saturation)              0
Dissolved Oxygen (%Saturation) [quality]    0
pH                                          0
pH [quality]                                0
Salinity                                    0
Salinity [quality]                          0
Specific Conductance                        0
Specific Conductance [quality]              0
Turbidity                                   0
Turbidity [quality]                         0
dtype: int64

In [61]:
# Normalization
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    if df[col].max() != df[col].min():
        df[col] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())

df.head()

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,0.000000,0.053764,0.204126,0.035208,NaN,0.200358,NaN,0.713002,NaN,0.599895,NaN,0.916490,NaN,0.978160,NaN,0.968458,NaN,0.034986,NaN
1,2023-08-04 23:30:00,0.000032,0.028294,0.295627,0.043031,NaN,0.198234,NaN,0.710273,NaN,0.596357,NaN,0.915433,NaN,0.977993,NaN,0.968313,NaN,0.033492,NaN
2,2023-08-04 23:00:00,0.000065,0.014014,0.435438,0.035184,NaN,0.199230,NaN,0.706260,NaN,0.592552,NaN,0.911205,NaN,0.977937,NaN,0.968276,NaN,0.034219,NaN
3,2023-08-04 23:30:00,0.000097,0.008453,0.782663,0.038448,NaN,0.198035,NaN,0.704494,NaN,0.590448,NaN,0.911205,NaN,0.978049,NaN,0.968367,NaN,0.033068,NaN
4,2023-08-04 23:00:00,0.000129,0.037781,0.679559,0.035532,NaN,0.198234,NaN,0.706100,NaN,0.592150,NaN,0.911205,NaN,0.977965,NaN,0.968295,NaN,0.032483,NaN

In [63]:
# Aggregation
agg_df = df.groupby(df.columns[0]).mean().reset_index()

agg_df.head()

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,0.000089,0.030827,0.399414,0.037100,NaN,0.196491,NaN,0.707905,NaN,0.593442,NaN,0.909091,NaN,0.978334,NaN,0.968613,NaN,0.034451,NaN
1,2023-08-04 23:30:00,0.000108,0.036799,0.490769,0.042615,NaN,0.194693,NaN,0.707277,NaN,0.592240,NaN,0.908034,NaN,0.978475,NaN,0.968737,NaN,0.033055,NaN
2,2023-08-05 00:00:00,0.000227,0.101633,0.144461,0.031087,NaN,0.187346,NaN,0.710915,NaN,0.593719,NaN,0.898520,NaN,0.979718,NaN,0.969823,NaN,0.034279,NaN
3,2023-08-05 00:30:00,0.000259,0.033166,0.258663,0.030856,NaN,0.186151,NaN,0.708828,NaN,0.591336,NaN,0.905920,NaN,0.979774,NaN,0.969859,NaN,0.033512,NaN
4,2023-08-05 01:00:00,0.000291,0.109563,0.147397,0.032384,NaN,0.183894,NaN,0.710112,NaN,0.591871,NaN,0.908034,NaN,0.980052,NaN,0.970114,NaN,0.033068,NaN

In [65]:
# Validation
validation = {
    "missing_values": df.isnull().sum(),
    "duplicates": df.duplicated().sum(),
    "shape": df.shape
}

validation

{'missing_values': Timestamp                                      0
 Record number                                  0
 Average Water Speed                           20
 Average Water Direction                        1
 Chlorophyll                                  585
 Chlorophyll [quality]                        808
 Temperature                                 5164
 Temperature [quality]                       5344
 Dissolved Oxygen                            4300
 Dissolved Oxygen [quality]                  4524
 Dissolved Oxygen (%Saturation)              5749
 Dissolved Oxygen (%Saturation) [quality]    5950
 pH                                          1084
 pH [quality]                                1308
 Salinity                                    3958
 Salinity [quality]                          4182
 Specific Conductance                        1367
 Specific Conductance [quality]              1591
 Turbidity                                   2000
 Turbidity [quality]                         2224
 dtype: int64,
 'duplicates': 0,
 'shape': (30894, 20)}

In [67]:
# large Data Analysis
chunks = pd.read_csv(r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv", chunksize=100000)

data = []

for chunk in chunks:
    chunk.fillna(chunk.mean(numeric_only=True), inplace=True)
    data.append(chunk)

df_large = pd.concat(data)

print("Large Data Shape:", df_large.shape)

Large Data Shape: (30894, 20)