In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql://postgres:#Twinkle65@localhost:5432/water_db")

In [11]:
# ETL Pipeline
# EXTRACT
df = pd.read_csv(r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv")

# TRANSFORM
df.fillna(df.mean(numeric_only=True), inplace=True)
df.drop_duplicates(inplace=True)
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

# LOAD
df.to_sql("water_data_etl", engine, if_exists="replace", index=False)

print("ETL Done")

ETL Done

In [17]:
# ELT Pipeline
# LOAD RAW
df_raw = pd.read_csv(r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv")
df_raw.to_sql("water_data_raw", engine, if_exists="replace", index=False)

# TRANSFORM IN SQL
with engine.connect() as conn:
    conn.execute(text('''
    CREATE TABLE water_data_elt AS
    SELECT 
        "Timestamp"::timestamp AS "Timestamp",
        COALESCE("Turbidity", 0) AS "Turbidity"
    FROM water_data_raw
    '''))
    conn.commit()

print("ELT Done")

ELT Done

In [7]:
pd.read_sql('SELECT * FROM water_data_etl LIMIT 5', engine)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,1468,4.834,73.484,1.621,1020.006648,20.018,1021.673973,7.472,1020.488055,101.175,1022.976668,8.176,1020.0,35.215,1020.0,53.262,1020.0,2.068,1020.0
1,2023-08-04 23:30:00,1469,2.544,106.424,1.959,1020.006648,19.986,1021.673973,7.455,1020.488055,100.884,1022.976668,8.175,1020.0,35.209,1020.0,53.254,1020.0,1.994,1020.0
2,2023-08-04 23:00:00,1470,1.260,156.755,1.620,1020.006648,20.001,1021.673973,7.430,1020.488055,100.571,1022.976668,8.171,1020.0,35.207,1020.0,53.252,1020.0,2.030,1020.0
3,2023-08-04 23:30:00,1471,0.760,281.754,1.761,1020.006648,19.983,1021.673973,7.419,1020.488055,100.398,1022.976668,8.171,1020.0,35.211,1020.0,53.257,1020.0,1.973,1020.0
4,2023-08-04 23:00:00,1472,3.397,244.637,1.635,1020.006648,19.986,1021.673973,7.429,1020.488055,100.538,1022.976668,8.171,1020.0,35.208,1020.0,53.253,1020.0,1.944,1020.0

In [9]:
pd.read_sql('SELECT * FROM water_data_elt LIMIT 5', engine)

            Timestamp  Turbidity
0 2023-08-04 23:00:00      2.068
1 2023-08-04 23:30:00      1.994
2 2023-08-04 23:00:00      2.030
3 2023-08-04 23:30:00      1.973
4 2023-08-04 23:00:00      1.944