In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:#Twinkle65@localhost:5432/water_db")

In [3]:
def batch_ingestion(file_path, table_name, batch_size=1000):
    chunks = pd.read_csv(file_path, chunksize=batch_size)
    
    for i, chunk in enumerate(chunks):
        print(f"Ingesting batch {i+1}")
        
        # basic cleaning (optional)
        chunk.fillna(chunk.mean(numeric_only=True), inplace=True)
        chunk.drop_duplicates(inplace=True)
        
        # load into database
        chunk.to_sql(table_name, engine, if_exists='append', index=False)

    print("Batch ingestion completed")

In [7]:
batch_ingestion(
    r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv",
    "water_data_batch",
    batch_size=1000
)

Ingesting batch 1
Ingesting batch 2
Ingesting batch 3
Ingesting batch 4
Ingesting batch 5
Ingesting batch 6
Ingesting batch 7
Ingesting batch 8
Ingesting batch 9
Ingesting batch 10
Ingesting batch 11
Ingesting batch 12
Ingesting batch 13
Ingesting batch 14
Ingesting batch 15
Ingesting batch 16
Ingesting batch 17
Ingesting batch 18
Ingesting batch 19
Ingesting batch 20
Ingesting batch 21
Ingesting batch 22
Ingesting batch 23
Ingesting batch 24
Ingesting batch 25
Ingesting batch 26
Ingesting batch 27
Ingesting batch 28
Ingesting batch 29
Ingesting batch 30
Ingesting batch 31
Batch ingestion completed

In [9]:
pd.read_sql("SELECT COUNT(*) FROM water_data_batch", engine)

   count
0  30894

In [11]:
pd.read_sql("SELECT table_name FROM information_schema.tables WHERE table_name='water_data_batch'", engine)

         table_name
0  water_data_batch