In [1]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\python\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\python\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\python\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\python\lib\site-packages (from sqlalchemy) (3.0.1)

In [3]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:#Twinkle65@localhost:5432/water_db")

In [9]:
import pandas as pd

df = pd.read_csv(r"C:\Water_Monitoring_System\data\brisbane_water_quality.csv")

df.head()

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,1468,4.834,73.484,1.621,NaN,20.018,NaN,7.472,NaN,101.175,NaN,8.176,NaN,35.215,NaN,53.262,NaN,2.068,NaN
1,2023-08-04 23:30:00,1469,2.544,106.424,1.959,NaN,19.986,NaN,7.455,NaN,100.884,NaN,8.175,NaN,35.209,NaN,53.254,NaN,1.994,NaN
2,2023-08-04 23:00:00,1470,1.260,156.755,1.620,NaN,20.001,NaN,7.430,NaN,100.571,NaN,8.171,NaN,35.207,NaN,53.252,NaN,2.030,NaN
3,2023-08-04 23:30:00,1471,0.760,281.754,1.761,NaN,19.983,NaN,7.419,NaN,100.398,NaN,8.171,NaN,35.211,NaN,53.257,NaN,1.973,NaN
4,2023-08-04 23:00:00,1472,3.397,244.637,1.635,NaN,19.986,NaN,7.429,NaN,100.538,NaN,8.171,NaN,35.208,NaN,53.253,NaN,1.944,NaN

In [11]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df.drop_duplicates(inplace=True)

In [13]:
df.to_sql("water_data", engine, if_exists="replace", index=False)

print("Data uploaded successfully")

Data uploaded successfully

In [35]:
pd.read_sql("SELECT * FROM water_data LIMIT 5", engine)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,1468,4.834,73.484,1.621,1020.006648,20.018,1021.673973,7.472,1020.488055,101.175,1022.976668,8.176,1020.0,35.215,1020.0,53.262,1020.0,2.068,1020.0
1,2023-08-04 23:30:00,1469,2.544,106.424,1.959,1020.006648,19.986,1021.673973,7.455,1020.488055,100.884,1022.976668,8.175,1020.0,35.209,1020.0,53.254,1020.0,1.994,1020.0
2,2023-08-04 23:00:00,1470,1.260,156.755,1.620,1020.006648,20.001,1021.673973,7.430,1020.488055,100.571,1022.976668,8.171,1020.0,35.207,1020.0,53.252,1020.0,2.030,1020.0
3,2023-08-04 23:30:00,1471,0.760,281.754,1.761,1020.006648,19.983,1021.673973,7.419,1020.488055,100.398,1022.976668,8.171,1020.0,35.211,1020.0,53.257,1020.0,1.973,1020.0
4,2023-08-04 23:00:00,1472,3.397,244.637,1.635,1020.006648,19.986,1021.673973,7.429,1020.488055,100.538,1022.976668,8.171,1020.0,35.208,1020.0,53.253,1020.0,1.944,1020.0

In [91]:
# WHERE
pd.read_sql('SELECT * FROM water_data WHERE "Turbidity" > 2', engine)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-04 23:00:00,1468,4.834,73.484,1.621,1020.006648,20.018,1021.673973,7.472,1020.488055,101.175,1022.976668,8.176,1020.0,35.215,1020.0,53.262,1020.0,2.068,1020.0
1,2023-08-04 23:00:00,1470,1.260,156.755,1.620,1020.006648,20.001,1021.673973,7.430,1020.488055,100.571,1022.976668,8.171,1020.0,35.207,1020.0,53.252,1020.0,2.030,1020.0
2,2023-08-04 23:00:00,1473,1.596,100.271,1.935,1020.006648,19.834,1021.673973,7.430,1020.488055,100.293,1022.976668,8.158,1020.0,35.255,1020.0,53.315,1020.0,2.124,1020.0
3,2023-08-05 00:00:00,1475,9.138,52.005,1.443,1020.006648,19.822,1021.673973,7.459,1020.488055,100.667,1022.976668,8.159,1020.0,35.271,1020.0,53.337,1020.0,2.033,1020.0
4,2023-08-05 01:30:00,1478,3.370,318.489,1.083,1020.006648,19.741,1021.673973,7.447,1020.488055,100.371,1022.976668,8.167,1020.0,35.290,1020.0,53.362,1020.0,2.014,1020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25651,2024-06-27 08:20:00,32357,13.314,82.720,0.944,1020.000000,18.607,1020.000000,6.876,1020.000000,87.556,1020.000000,8.151,1020.0,29.268,1020.0,45.134,1020.0,3.963,1020.0
25652,2024-06-27 08:30:00,32358,32.617,18.081,1.161,1020.000000,18.551,1020.000000,6.918,1020.000000,87.987,1020.000000,8.163,1020.0,29.254,1020.0,45.115,1020.0,3.928,1020.0
25653,2024-06-27 08:40:00,32359,8.552,306.184,1.192,1020.000000,18.558,1020.000000,6.651,1020.000000,84.606,1020.000000,8.145,1020.0,29.250,1020.0,45.110,1020.0,4.097,1020.0
25654,2024-06-27 08:50:00,32360,10.341,24.711,1.031,1020.000000,18.547,1020.000000,6.740,1020.000000,85.713,1020.000000,8.154,1020.0,29.247,1020.0,45.105,1020.0,4.962,1020.0
25655,2024-06-27 09:00:00,32361,11.173,241.662,0.946,1020.000000,18.562,1020.000000,5.842,1020.000000,74.326,1020.000000,8.116,1020.0,29.258,1020.0,45.121,1020.0,5.078,1020.0

In [93]:
# GROUP BY
pd.read_sql('''
SELECT "Timestamp", AVG("Turbidity")
FROM water_data
GROUP BY "Timestamp"
''', engine)

                 Timestamp        avg
0      2024-02-24 17:20:00   6.425000
1      2023-12-13 22:10:00   0.739000
2      2024-02-09 18:50:00   3.745000
3      2024-04-10 22:40:00  17.076000
4      2023-11-13 08:30:00   3.941688
...                    ...        ...
30609  2024-06-14 05:50:00   3.148000
30610  2024-06-08 17:20:00   4.387000
30611  2023-11-12 03:00:00   3.941688
30612  2023-09-05 02:30:00   1.924000
30613  2023-12-25 10:10:00   1.603000

[30614 rows x 2 columns]

In [95]:
# ORDER BY
pd.read_sql('''
SELECT * FROM water_data
ORDER BY "Timestamp" DESC
''', engine)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2024-06-27 09:00:00,32361,11.173,241.662,0.946,1020.000000,18.562,1020.000000,5.842,1020.000000,74.326,1020.000000,8.116,1020.0,29.258,1020.0,45.121,1020.0,5.078,1020.0
1,2024-06-27 08:50:00,32360,10.341,24.711,1.031,1020.000000,18.547,1020.000000,6.740,1020.000000,85.713,1020.000000,8.154,1020.0,29.247,1020.0,45.105,1020.0,4.962,1020.0
2,2024-06-27 08:40:00,32359,8.552,306.184,1.192,1020.000000,18.558,1020.000000,6.651,1020.000000,84.606,1020.000000,8.145,1020.0,29.250,1020.0,45.110,1020.0,4.097,1020.0
3,2024-06-27 08:30:00,32358,32.617,18.081,1.161,1020.000000,18.551,1020.000000,6.918,1020.000000,87.987,1020.000000,8.163,1020.0,29.254,1020.0,45.115,1020.0,3.928,1020.0
4,2024-06-27 08:20:00,32357,13.314,82.720,0.944,1020.000000,18.607,1020.000000,6.876,1020.000000,87.556,1020.000000,8.151,1020.0,29.268,1020.0,45.134,1020.0,3.963,1020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30889,2023-08-04 23:30:00,1471,0.760,281.754,1.761,1020.006648,19.983,1021.673973,7.419,1020.488055,100.398,1022.976668,8.171,1020.0,35.211,1020.0,53.257,1020.0,1.973,1020.0
30890,2023-08-04 23:00:00,1472,3.397,244.637,1.635,1020.006648,19.986,1021.673973,7.429,1020.488055,100.538,1022.976668,8.171,1020.0,35.208,1020.0,53.253,1020.0,1.944,1020.0
30891,2023-08-04 23:00:00,1468,4.834,73.484,1.621,1020.006648,20.018,1021.673973,7.472,1020.488055,101.175,1022.976668,8.176,1020.0,35.215,1020.0,53.262,1020.0,2.068,1020.0
30892,2023-08-04 23:00:00,1470,1.260,156.755,1.620,1020.006648,20.001,1021.673973,7.430,1020.488055,100.571,1022.976668,8.171,1020.0,35.207,1020.0,53.252,1020.0,2.030,1020.0
30893,2023-08-04 23:00:00,1473,1.596,100.271,1.935,1020.006648,19.834,1021.673973,7.430,1020.488055,100.293,1022.976668,8.158,1020.0,35.255,1020.0,53.315,1020.0,2.124,1020.0

In [97]:
# Subquery
pd.read_sql('''
SELECT * FROM water_data
WHERE "Turbidity" > (
    SELECT AVG("Turbidity") FROM water_data
)
''', engine)

,Timestamp,Record number,Average Water Speed,Average Water Direction,Chlorophyll,Chlorophyll [quality],Temperature,Temperature [quality],Dissolved Oxygen,Dissolved Oxygen [quality],Dissolved Oxygen (%Saturation),Dissolved Oxygen (%Saturation) [quality],pH,pH [quality],Salinity,Salinity [quality],Specific Conductance,Specific Conductance [quality],Turbidity,Turbidity [quality]
0,2023-08-05 14:30:00,1504,4.416,333.348,2.782251,1020.006648,24.415394,1021.673973,6.815158,1020.488055,96.641207,1022.976668,8.06326,1020.0,31.003265,1020.0,47.927487,1020.0,3.941688,1020.0
1,2023-08-06 03:30:00,1530,3.390,150.115,1.238000,1020.006648,19.851000,1021.673973,6.797000,1020.488055,91.788000,1022.976668,8.17300,1020.0,35.258000,1020.0,53.320000,1020.0,8.774000,1020.0
2,2023-08-09 04:30:00,1676,1.056,179.040,2.653000,1020.006648,18.802000,2010.000000,6.787000,1020.488055,89.596000,2010.000000,8.17200,1020.0,34.724000,1020.0,52.599000,1020.0,4.445000,1020.0
3,2023-08-10 03:00:00,1721,4.582,135.098,3.009000,1020.000000,19.170000,1020.000000,7.307000,1020.000000,97.223000,1020.000000,8.17000,1020.0,34.898000,1020.0,52.833000,1020.0,4.120000,1020.0
4,2023-08-10 04:30:00,1724,3.183,266.311,3.398000,1020.000000,19.051000,1020.000000,7.333000,1020.000000,97.355000,1020.000000,8.16800,1020.0,34.883000,1020.0,52.813000,1020.0,5.209000,1020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9533,2024-06-27 08:10:00,32356,19.689,33.866,1.264000,1020.000000,18.628000,1020.000000,6.796000,1020.000000,86.583000,1020.000000,8.15900,1020.0,29.288000,1020.0,45.162000,1020.0,4.110000,1020.0
9534,2024-06-27 08:20:00,32357,13.314,82.720,0.944000,1020.000000,18.607000,1020.000000,6.876000,1020.000000,87.556000,1020.000000,8.15100,1020.0,29.268000,1020.0,45.134000,1020.0,3.963000,1020.0
9535,2024-06-27 08:40:00,32359,8.552,306.184,1.192000,1020.000000,18.558000,1020.000000,6.651000,1020.000000,84.606000,1020.000000,8.14500,1020.0,29.250000,1020.0,45.110000,1020.0,4.097000,1020.0
9536,2024-06-27 08:50:00,32360,10.341,24.711,1.031000,1020.000000,18.547000,1020.000000,6.740000,1020.000000,85.713000,1020.000000,8.15400,1020.0,29.247000,1020.0,45.105000,1020.0,4.962000,1020.0
9537,2024-06-27 09:00:00,32361,11.173,241.662,0.946000,1020.000000,18.562000,1020.000000,5.842000,1020.000000,74.326000,1020.000000,8.11600,1020.0,29.258000,1020.0,45.121000,1020.0,5.078000,1020.0

In [109]:
# Creating Second table 
with engine.connect() as conn:
    conn.execute(text('''
    CREATE TABLE time_info (
        "Timestamp" TIMESTAMP,
        "Category" VARCHAR(50)
    )
    '''))
    conn.commit()

In [113]:
with engine.connect() as conn:
    conn.execute(text(f'''
    INSERT INTO time_info ("Timestamp", "Category") VALUES
    ('{df["Timestamp"][0]}', 'Normal'),
    ('{df["Timestamp"][1]}', 'Alert'),
    ('{df["Timestamp"][2]}', 'Critical')
    '''))
    conn.commit()

In [115]:
# Left Join
pd.read_sql('''
SELECT w."Timestamp", w."Turbidity", t."Category"
FROM water_data w
JOIN time_info t
ON w."Timestamp" = t."Timestamp"::text
''', engine)

              Timestamp  Turbidity  Category
0   2023-08-04 23:00:00      2.124    Normal
1   2023-08-04 23:00:00      1.944    Normal
2   2023-08-04 23:00:00      2.030    Normal
3   2023-08-04 23:00:00      2.068    Normal
4   2023-08-04 23:30:00      1.950     Alert
5   2023-08-04 23:30:00      1.973     Alert
6   2023-08-04 23:30:00      1.994     Alert
7   2023-08-04 23:00:00      2.124  Critical
8   2023-08-04 23:00:00      1.944  Critical
9   2023-08-04 23:00:00      2.030  Critical
10  2023-08-04 23:00:00      2.068  Critical

In [117]:
# Window functions 
pd.read_sql('''
SELECT 
    "Timestamp",
    "Turbidity",
    RANK() OVER (
        ORDER BY "Turbidity" DESC
    ) AS rank
FROM water_data
''', engine)

                 Timestamp  Turbidity   rank
0      2024-04-15 04:00:00     49.869      1
1      2024-05-20 05:40:00     49.427      2
2      2024-05-20 20:40:00     48.902      3
3      2024-05-19 05:20:00     48.697      4
4      2024-04-08 17:20:00     48.592      5
...                    ...        ...    ...
30889  2023-12-03 22:00:00      0.370  30890
30890  2023-12-03 23:00:00      0.365  30891
30891  2023-12-01 02:00:00      0.359  30892
30892  2023-12-02 04:00:00      0.345  30893
30893  2023-12-01 00:30:00      0.335  30894

[30894 rows x 3 columns]

In [123]:
 # OLAP
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text('''
    CREATE TABLE water_summary AS
    SELECT 
        DATE("Timestamp"::timestamp) AS date,
        AVG("Turbidity") AS avg_turbidity,
        AVG("Temperature") AS avg_temperature,
        AVG("pH") AS avg_ph
    FROM water_data
    GROUP BY DATE("Timestamp"::timestamp)
    '''))
    conn.commit()

In [89]:
pd.read_sql('SELECT * FROM water_summary', engine)

           date  avg_turbidity  avg_temperature    avg_ph
0    2023-08-04       2.011857        19.948143  8.168571
1    2023-08-05       2.084577        20.033696  8.161714
2    2023-08-06       1.932333        19.893917  8.166021
3    2023-08-07       1.720875        19.165583  8.176604
4    2023-08-08       1.858396        19.177083  8.172417
..          ...            ...              ...       ...
293  2024-06-23       2.774897        21.455434  8.180393
294  2024-06-24       2.922425        20.902884  8.187448
295  2024-06-25       3.092083        18.947180  8.171855
296  2024-06-26       3.775572        18.563855  8.166510
297  2024-06-27       4.184345        18.913345  8.157000

[298 rows x 4 columns]